### ISSUE TITLE
How to Select COM port

### ISSUE THREAD

**Issue by sakthimaan** [cpwood/Pico-Go#12]
Not able to select the COM Port. Extension is automatically choosing the COM port. 

![image](https://user-images.githubusercontent.com/14888257/106995155-4a132c00-67a4-11eb-8920-f771a44c81cf.png)

**Comment by sakthimaan** [comment]
Note: Pico is connected to COM 4.

**Comment by cpwood** [comment]
This is now next on my list, but I'll be unavailable for a few days.

**Comment by snympi** [comment]
This would be useful to me as well, thanks @cpwood

**Comment by cpwood** [comment]
Development is done; I just need to spend some time testing it.

Your global config (`Ctrl+Shift+G` or `Command+Shift+G`) will need to change in a way similarl to the following on macOS or Linux:

```json
	"auto_connect": false,
	"manual_com_device": "/dev/tty.usbmodem0000000000001",
```

or similar to the following on Windows:

```json
	"auto_connect": false,
	"manual_com_device": "COM3",
```

**Comment by sakthimaan** [comment]
@cpwood 
Awesome.. thanks for fixing this issue. 👍

**Comment by adarmaori** [comment]
When I did this and tried to connect the output was ```"Address not configured. Please go to the settings to configure a valid address or comport"```. This is the relevant part of my global settings file:
```
"auto_connect": false,
"manual_com_device": "COM5",
```
Did I do something wrong or is this a bug?

**Comment by kbreezy04** [comment]
> When I did this and tried to connect the output was `"Address not configured. Please go to the settings to configure a valid address or comport"`. This is the relevant part of my global settings file:
> 
> ```
> "auto_connect": false,
> "manual_com_device": "COM5",
> ```
> 
> Did I do something wrong or is this a bug?

I also get this.  Project settings are also not respected for me.

**Comment by sotnyk-lv** [comment]
Ctrl+Shift+G is opening Source Control for me.

Where or how I can find this global config file?

**Comment by YayoVera26** [comment]
could you connect to your pico COM, I got the same error, address not configured.

**Comment by YayoVera26** [comment]
Update, I was able to connect my pi pico to the VS, my solution:

If you have Bluetooth on your computer/laptop, try disabling it if you have it enabled this causes you to have more ports in use, by disabling it VS will recognize your pi pico as it is the only COM available.

Hope it works for you.

**Comment by Anshuman-UCSB** [comment]
> 

This worked for me, seems that the settings were not respected and it kept defaulting to COM3 which was bluetooth

**Comment by Elephant42** [comment]
Same here as others have reported.
Made the recommended change to global config
"auto_connect": false,
"manual_com_device": "COM7",
but keep getting the "address not configured" error.
I have several COM ports active as well as the Pico - I'm on Windows 10 Pro BTW.
