### ISSUE TITLE
Compatibility issue in VS Code 1.53.0 on Raspberry Pi OS

### ISSUE THREAD

**Issue by andypiper** [cpwood/Pico-Go#17]
When I open a Terminal per the second part of your tutorial, I'm seeing

```
This version of Pico-Go is incompatible with VSCode 1.53.0. Check for an update to the extension. If one isn't available, raise a bug at https://github.com/cpwood/Pico-Go to get this fixed!
```

**Comment by andypiper** [comment]
Also:

`Command 'Pico-Go > Connect' resulted in an error (command 'pymakr.connect' not found)`

When executed from the quick command bar.

**Comment by cpwood** [comment]
@andypiper closing this one as it's more the current state of play - arm64 just isn't supported at the moment - however, I'm about to tag you into something else, so all is not lost!
