### ISSUE TITLE
Include stubs within Pico-Go

### ISSUE THREAD

**Issue by cpwood** [cpwood/Pico-Go#24]
Make it easier to get going: add a command palette option to install the stubs and linting for a new project.

Workflow should be:

1. Create a new folder and open it in VS Code.
2. From the Command Palette (`ctrl-shift-p` or `command-shift-p`), choose `Pico-Go > Configure Project`.
3. Create a `.py` file and start coding!

**Comment by snympi** [comment]
Useful additional feature. Would simplify my workflow.
