### ISSUE TITLE
COM port specification in pico-go.json and pymakr.conf not working

### ISSUE THREAD

**Issue by snympi** [cpwood/Pico-Go#27]
## What are the steps to reproduce this issue?
1. Connect Pi Pico to COM port with high number, e.g. COM8
2. Connect other serial board e.g. ESP32, Meadow etc. to lower COM port, e.g. COM5
3. Make sure both boards report 'Microsoft' as manufacturer
4. Pico-Go always tries to connect to lower COM port number
5. Change specification in pico-go.json (global config) and pymakr.conf (local config) to use COM8, by adding "address": "COM8", - this is according to the Pymakr documentation
6. Disable autoconnect by changing "auto_connect": false, in pico-go.json - also according to Pymakr support to ensure that address specification is respected
7. Pico-Go does not attempt auto connection any more, but when Pico-Go > Connect command is issued, it stil tries to connect to COM5

## What happens?
COM port address specification is ignored, even when global auto_connect is disabled.

## What were you expecting to happen?
Connection to COM8

## Any logs, error output, etc?
Connecting to COM5...
> Failed to connect (Error: Port is not open). Click the "Pico Disconnected" button to try again.

## Any other comments?
Same problem is resolved in Pymakr by disabling auto_connect

## Which versions of software are you using?

Operating system: Windows 10, 19042.685

VSCode version: 1.53.2

Pico-Go version: 1.0.8

## Which hardware are you using?
Raspberry Pi Pico or the name of another RP2040 board.

**Comment by cpwood** [comment]
I'm afraid you're not configuring things correctly; it differs slightly to Pymakr. 

You'll need to set `auto_connect` to false and then set `manual_com_device` to your COM port value. 

You can only do this in the global configuration.
