### ISSUE TITLE
RUN enhancement

### ISSUE THREAD

**Issue by sstaub** [cpwood/Pico-Go#33]
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
When you RUN a program and change the file you have to stop the execution first doing RUN again or CTRL+C before you can start the program with RUN again

## Describe the solution you'd like
When a program is running and you change the file, RUN should work immediately without stopping the program manually.
This should done automatically.

**Comment by cpwood** [comment]
Thanks, @sstaub. I think this ticket is incongruous with #34, if I understand correctly. I.e. if the "Run" button changes to "Stop" (as requested in #34), by definition you can't run something again until you've stopped it anyway.

Closing on that basis, but I'm about to respond on #34 with some good news.
