### ISSUE TITLE
REPL while running

### ISSUE THREAD

**Issue by sstaub** [cpwood/Pico-Go#34]
# Feature Request 🚀

## Is your feature request related to a problem? Please describe.
If a program is running you have to stop it before you can use the REPL, this can be done with pressing RUN again or CTRL+C

## Describe the solution you'd like
A dedicated button naming STOP or REPL would be more intuitive, maybe also a symbol (stop) when execution is stopped.

**Comment by cpwood** [comment]
Thanks, @sstaub! This is actually a bug as it _should_ already be doing this! Looks like a bug inherited from Pymakr.

The good news is that the code is now complete and it will be included in version 1.1.1.

**Comment by cpwood** [comment]
Thanks for your patience. This is still coming, but I really want to get #35 finished before it's released.

**Comment by sstaub** [comment]
No problem, I will start a pico project in a couple of weeks because I have to finish another project first.
