### ISSUE TITLE
Cosmetic: change "run" icon

### ISSUE THREAD

**Issue by cpwood** [cpwood/Pico-Go#48]
It's currently a right-facing triangle, but there is a `start` icon that would be more appropriate.

**Comment by sstaub** [comment]
Maybe a green filled start and a red filled stop button will hepfull

**Comment by cpwood** [comment]
@sstaub we're limited to the [VS Code icon set](https://code.visualstudio.com/api/references/icons-in-labels), really.

**Comment by sstaub** [comment]
There are the new 'product icon theme' which allows own defined icons, but only with one color, but there is the possibility to change the background color of the status bar.
https://code.visualstudio.com/api/extension-guides/product-icon-theme
