### ISSUE TITLE
Pico Console not updating at runtime with print() statements

### ISSUE THREAD

**Issue by kevindawson** [cpwood/Pico-Go#51]
## What are the steps to reproduce this issue?
I have an example for you
```python
# pico-001.py

import random
import usys
from utime import sleep_ms, sleep
from machine import ADC, Pin

onboard_temp_sensor = ADC(4)
onboard_p25_led = Pin(25, Pin.OUT)
conversion_factor = 3.3 / (65535)
ON = True
OFF = False


def onboard_led(state):
    if state is True:
        onboard_p25_led.value(1)
        # led.high() additional for Pico
        sleep_ms(222)
    else:
        onboard_p25_led.value(0)
        # led.low() additional for Pico
        sleep_ms(181)


def onboard_temp():
    current_voltage = onboard_temp_sensor.read_u16() * conversion_factor
    return 27 - ((current_voltage - 0.706) / 0.001721)


def main():
    print("hello\n")

    for _ in range(random.randint(3, 5)):
        onboard_led(ON)
        # degres in unicode -> \u00b0 -> °
        print("Pico onboard temp is: %2.1f\u00b0C" % onboard_temp())
        onboard_led(OFF)
        sleep(1)


if __name__ == "__main__":
    main()
    print("\n\tSo long and Thanks for all the Fish!\n")
    usys.exit(0)

```

## What happens?
Pico Console updates on completion

## What were you expecting to happen?
Pico Console to update while script running

## Any logs, error output, etc?
n/a

## Support info

```
Pico-Go:      1.2.1
VS Code:      1.54.1
Electron:     11.3.0
Modules:      85
Node:         12.18.3
Platform:     linux
Architecture: x64
Board:        Raspberry Pi Pico with RP2040
Firmware:     v1.14 on 2021-02-24 (GNU 10.2.0 MinSizeRel)
```

**Comment by cpwood** [comment]
Thanks for this! Can you confirm how you're executing it? Are you click the `Run` button _or_ transferring it to the board and calling it `main.py`, for example?

**Comment by cpwood** [comment]
Think I've got this working a little better:

![2021-03-07 09 07 27](https://user-images.githubusercontent.com/13966104/110234849-bb213d00-7f24-11eb-94da-9921bc6ad62e.gif)

Needs a bit more testing yet though.

**Comment by kevindawson** [comment]
Just ```Run``` Button

- nice gif above:)
- running as it did in previous versions

Cool

So long and Thanks for all the Fish!

**Comment by kevindawson** [comment]
@cpwood 
re: Needs a bit more testing yet though.

I  have some time today to test if you want, just point the way

**Comment by cpwood** [comment]
Might be a little bit late in the day, depending upon where you are in the world, but if you fancied having a play with version 1.2.2, I'd appreciate your feedback!

You can download it [here](https://cwood.blob.core.windows.net/temp/pico-go-1.2.2.vsix); I haven't uploaded it to the Marketplace just yet.

It's been a pretty tough fix, believe it or not. I got it working as per the GIF above fairly easily, but that then broke everything else (e.g. deleting files, uploading or downloading the project, etc). Hopefully cracked it now though.

I've also done quite a bit of work on reducing the CPU load of the extension.

**Comment by kevindawson** [comment]
@cpwood 

beta 1.2.2

Nice One ;)

- CPU load of the extension - Looks like you killed the Hog - now 2% constant ;)
- able to Ctrl+C out of running code

have you ever considered displaying files on Pico with  ```print('uos.listdir :   ' + str(uos.listdir()))```

**Comment by cpwood** [comment]
@kevindawson I've got something else up my sleeve for managing files 😉 Watch this space.

Thanks for the feedback; I'll upload it to the Marketplace tomorrow evening (UK time) assuming I don't find any gremlins before then.

**Comment by kevindawson** [comment]
@cpwood 

Cool - is there any other time but GMT (primary time zone like yourself:)
So long and Thanks for all the Fish!
