### ISSUE TITLE
"stubs" folder doesn't exist in  "Pico-Stub-main" folder...

### ISSUE THREAD

**Issue by Sadudu** [cpwood/Pico-Go#67]
Hello. 

Sorry to disturb you for asking a question about your extension of "PICO-GO". In the guide website"https://medium.com/all-geek-to-me/developing-for-the-raspberry-pi-pico-in-vs-code-getting-started-6dbb3da5ba97", everything is success expect the step: "Configuring Micropy CLI".

I found there is no stubs folder in the download link, can you upload this folder again?

Thank you.

**Comment by cpwood** [comment]
If recommend following the guidance at http://pico-go.net - that article is already out-of-date.

It's far easier to get up and running these days.
