### ISSUE TITLE
Update stubs for Firmware 1.15.0

### ISSUE THREAD

**Issue by cpwood** [cpwood/Pico-Go#85]
Firmware 1.15 was released on 18 April 2021. Stubs need updating accordingly once Pico-Stub is updated.

**Comment by Lak4CYUT** [comment]
Hi cpwood,
Is the Pin.__call__ mthod missing here? I cannot find it on machine.pyi, it will cause IDE throw a error..
https://docs.micropython.org/en/v1.15/library/machine.Pin.html?highlight=class%20pin#machine.Pin.__call__
