### ISSUE TITLE
Compatablity issue - VS Code 1.59.0...

### ISSUE THREAD

**Issue by kevindawson** [cpwood/Pico-Go#99]
## What are the steps to reproduce this issue?
1. upgrade vsc 1.59.0

## What happens?
absolutely nothing

## What were you expecting to happen?
vsc upgrade and Pico-go in harmony

## Any other comments?
Keep up the good work, its just a mater of time

## Support info

Pico-Go:      1.4.2
VS Code:      1.58.2
Electron:     12.0.13
Modules:      87
Node:         14.16.0
Platform:     linux
Architecture: x64
Board:        Raspberry Pi Pico with RP2040
Firmware:     v1.16 on 2021-06-29 (GNU 10.2.0 MinSizeRel)

**Comment by WojTechnical** [comment]
Yep, it's the same bug as the one I created earlier, 1.59.0 isn't compatible unless the bindings.node file gets updated to support it....

https://github.com/cpwood/Pico-Go/issues/98

**Comment by cpwood** [comment]
Closing as a duplicate.

**Comment by cpwood** [comment]
Fixed v.1.43.

**Comment by kevindawson** [comment]
@WojTechnical sorry for the duplicate issue
@cpwood my bad
